### ISSUE TITLE
Backend plugin epic

### ISSUE THREAD

**Issue by alexanderzobnin** [alexanderzobnin/grafana-zabbix#798]
This is epic issue for all initial backend plugin implementation work.

- [x] Simple backend plugin that proxy all queries
- [x] Authentication on the backend (#799, #800)
- [x] Cache for requests (#802)
- [x] Per-datasource cache and auth storage (#812)
- [x] Initial alerting queries (#801)
- [ ] ~~Functions support on the backend (#869)~~ (Moved to 4.1)

**Comment by axute** [comment]
So I would be very interested in the last point. I use the functions (scale, offset ...) very diligently, but then I cannot set an alarm.

**Comment by alexanderzobnin** [comment]
Yes, functions is the next task in my backend backlog, so hope I can (start at least) do it soon.
